GET http://localhost:3001/api/blogs HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVjcmlzdG9iYWwiLCJpZCI6IjYwZTVjNDUxZWQxYmE1Yjk1ZTVmNzNlNSIsImlhdCI6MTYyNTY3ODA3OX0.UrkgC-70Ur493dz7PjqBo9al3V8cBKOid5wX41v8yro

